### ISSUE TITLE
home brew installer partition function should print the current partition list so that the user can see what them as is

### ISSUE THREAD

**Issue by mdheller** [SociOS-Linux/socios-setup#3]
The installer should recommend sizings for Swap, and other partitions which will need to be created as well. Please make sure to provide the user with these details as part of the workflow once they see the tables and are given the option not proceed with default partition-scheme or if they would like to implement a custom scheme.

What is the complexity of this/these?. What is hours estimate? How is it tracking? @Anilkumar18 

Complexity time: 2
Estimated Time: (2hr to 4hrs)
Tracking:  We will update the GitHub task card and create a branch called socios #3 so that you can track the work done for a card to a specific branch / pull request / merge.
@mdheller

**Comment by Anilkumar18** [comment]
We have updated the script for listing out the disk space available on the user machine and they can able to select the disk from the list and input the custom size of the disk space while doing the partition.

**diskutil list
    echo "Provide the disk space want to use for the above list"**

```
if [ $Input == 1 ]
then
    echo "Resizing the APFS container for partition $default_disk $default_size"
    diskutil apfs resizeContainer $default_disk $default_size
else
    diskutil list
    echo "Provide the disk space want to use for the above list"
    read -p "Provide the disk space want to use for Linux OS" disk_input
    read -p "Provide the disk space want to allocate for Linux OS in GB(e.g:30g)" size_input
    diskutil apfs resizeContainer "$disk_input" "$size_input"
fi
```

**Comment by mdheller** [comment]
Is this done? This looks like a 30 minute job to update... what am I missing? this is two weeks old. @Anilkumar18
