### ISSUE TITLE
Documentation for script and implementation:

### ISSUE THREAD

**Issue by Anilkumar18** [SociOS-Linux/socios-setup#7]
- [x] Document the steps used for creating the script and implementing it on the Mac machine.

I would like for there to be several sections for the documentation that follows the follow the same pattern here: https://github.com/giantswarm/gsctl/tree/main/docs

Anyone on the internet should be able to type brew tap SociOS-Linux/socios && brew install socios ; and after doing so it should be really easy for them to use the installer. 

I've asked a few folks to document their issues and I'll share more soon, but the instructions in the repo are not focused on how to install and use the script but instead focus on cloning the contents and adding it to git... there should be a docs folder which contains various .md files.
the repo here is a good example:
https://github.com/giantswarm/gsctl/tree/main/docs 
-Development.md page: https://github.com/SociOS-Linux/gsctl/blob/main/docs/Development.md

-Release.md page:
https://github.com/SociOS-Linux/gsctl/blob/main/docs/Release.md

-Command-Blueprint.md https://github.com/SociOS-Linux/gsctl/blob/main/docs/Command-Blueprint.md

--Contributing.md 
https://github.com/giantswarm/gsctl/blob/main/CONTRIBUTING.md

Please notice that for each action/function in the script, they created a .md file corresponding to this function / action--I would like to see all of our documentation mirror this and we should adopt their conventions going forward.

https://github.com/giantswarm/docs/tree/main/src/content/ui-api/gsctl

**Comment by mdheller** [comment]
Second priority
